apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"
      containers:
      - name: openldap
        image: osixia/openldap:latest
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        env:
        - name: LDAP_ORGANISATION
          value: "sesac-univ"
        - name: LDAP_DOMAIN
          value: "sesac-univ.click"
        - name: LDAP_ADMIN_PASSWORD
          value: "asdf10023!"
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: openldap
spec:
  type: LoadBalancer
  ports:
  - port: 389
    targetPort: 389
    protocol: TCP
    name: ldap
  - port: 636
    targetPort: 636
    protocol: TCP
    name: ldaps
  selector:
    app: openldap